#!/bin/sh
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2013 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson
#

name=$(basename $0)

if [ -z $SA_AMF_COMPONENT_NAME ]; then
	logger -st $name "not AMF component context"
	exit 199
fi

RETVAL=0

cleanup()
{
	logger -st $name "cleanup $SA_AMF_COMPONENT_NAME"
	return $RETVAL
}

status()
{
	RETVAL=$?
	return $RETVAL
}

CMD=$1
case $CMD in
	cleanup)
		cleanup $*
		RETVAL=$?
		;;
	status)
		status
		RETVAL=$?
		;;
	*)
		echo "Usage: $0 {cleanup}"
		RETVAL=2
esac

exit $RETVAL

